[package]
name = "csync"
version = "0.1.0"
edition = "2024"

[lib]
name = "csync"
path = "src/lib.rs"

[[bin]]
name = "csync"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
filetime = "0.2.25"
ignore = "0.4.23"
notify = "8.0.0"
tracing = "0.1.41"
tracing-subscriber = {  version = "0.3.19", features = ["env-filter"] }
anyhow = "1.0.98"
rayon = "1.10.0"


[dev-dependencies]
tempfile = "3.14.0"
walkdir = "2.5.0"

[build-dependencies]
clap = { version = "4.5.36", features = ["derive"] }
clap_complete = "4.5.36"
